projects:
  airbnbclone:
    schemaPath: src/graphql/schema.json
    includes:
      - src/schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api.ts
        docsFilePath: src
